### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by antbag-dev** [MrEcstsy/AdvancedEnchantments#1]
[11:50:52.805] [Server thread/CRITICAL]: Error: "Class "ecstsy\AdvancedEnchantments\utils\LanguageManager" not found" (EXCEPTION) in "plugins/AdvancedEnchantments_dev-50.phar/src/ecstsy/AdvancedEnchantments/Loader" at line 54
--- Stack trace ---
  #0 pmsrc/src/plugin/PluginBase(119): ecstsy\AdvancedEnchantments\Loader->onEnable()
  #1 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #2 pmsrc/src/Server(1404): pocketmine\plugin\PluginManager->enablePlugin(object ecstsy\AdvancedEnchantments\Loader#47057)
  #3 pmsrc/src/Server(1035): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#50234)
  #4 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
  #5 pmsrc/src/PocketMine(378): pocketmine\server()
  #6 /home/container/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMP6T3FBg.tar/src/PocketMine.php)
--- End of exception information ---

**Comment by MrEcstsy** [comment]
Should be fixed with dev build #58

https://poggit.pmmp.io/ci/MrEcstsy/AdvancedEnchantments/AdvancedEnchantments/dev:58
